#cloud-config
hostname: worker-1
fqdn: worker-1.k8s.local
manage_etc_hosts: true

timezone: America/Sao_Paulo

users:
  - name: root
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtCJ65yvOSSxSECjvO5S2ttEjlcunKLfXhnq4ob1ijf leona@Leonas-Mac-mini.local
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtCJ65yvOSSxSECjvO5S2ttEjlcunKLfXhnq4ob1ijf leona@Leonas-Mac-mini.local

ssh_pwauth: false
disable_root: false

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - curl
  - ca-certificates
  - apt-transport-https

runcmd:
  - systemctl enable --now qemu-guest-agent
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - sysctl -p